version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "1433:1433"
    volumes:
      - mssql2019:/var/opt/mssql
    environment:
        SA_PASSWORD: "sqlserver@123"
        ACCEPT_EULA: "Y"

volumes:
  mssql2019:
    driver: local